services:
  - type: web
    name: deepsea-sentiment
    env: python
    region: singapore

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"

    plan: free

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
